config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :posts do
    resources :comments, shallow: true do
      delete :destroy_all, on: :collection
    end
    resources :images, shallow: true
  end

  resources :comments, only: [:new]
  resources :users

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  validates :user_id, presence: true

  attr_accessor :author_name, :author_city
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    get_all_users
    respond_to do |format|
        format.html {}
        format.json  {
        }
     end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
      format.html { }
      format.json { }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
    get_all_users
  end

  # GET /posts/1/edit
  def edit
    get_all_users
  end

  # POST /posts
  # POST /posts.json
  def create
    get_all_users
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
  
    def get_all_users
      @users = User.all
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br/>
    <%= f.select :user_id, options_for_select(@users.map { |user| [user.name, user.id]}, @post.user_id) %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> | 
<%= link_to 'Back to MAIN', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User: </strong>
  <td><%= @post.user.name %></td>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image:</strong> <br/>
   <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Picture</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @post.images.each do |picture| %>
        <tr>
          <td><%= link_to image_tag(picture.attachment_url(:thumb)), picture.attachment_url %></td>
          <td><%= button_to "Delete", image_path(id: picture.id), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>


<p>
  <%= link_to "Add Picture", new_post_image_path(@post), class: "btn btn-info" %>
</p>

<%= link_to pluralize(@post.comments.size, 'comment'), post_comments_path(@post) %> |

<%= link_to( "Delete all comments", destroy_all_post_comments_path(post_id: @post.id), method: :delete) %> |

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>